"""Rename table user to tq_user to avoid problems using a reserved word.

Revision ID: 133552773f96
Revises: 1e5ff49ec9ef
Create Date: 2015-11-15 16:59:57.328097

"""

# revision identifiers, used by Alembic.
revision = '133552773f96'
down_revision = '1e5ff49ec9ef'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tq_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=80), nullable=False),
    sa.Column('user_name', sa.String(length=70), nullable=True),
    sa.Column('user_github_id', sa.Integer(), nullable=False),
    sa.Column('user_github_login', sa.String(length=80), nullable=False),
    sa.Column('user_created', sa.DateTime(), nullable=False),
    sa.Column('user_is_active', sa.Boolean(), nullable=True),
    sa.Column('user_is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_github_id'),
    sa.UniqueConstraint('user_github_login')
    )
    op.drop_constraint(u'quote_user_id_fkey', 'quote', type_='foreignkey')
    op.create_foreign_key(None, 'quote', 'tq_user', ['user_id'], ['user_id'])
    op.drop_constraint(u'role_user_id_fkey', 'role', type_='foreignkey')
    op.create_foreign_key(None, 'role', 'tq_user', ['user_id'], ['user_id'])
    op.drop_table('user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.create_foreign_key(u'role_user_id_fkey', 'role', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'quote', type_='foreignkey')
    op.create_foreign_key(u'quote_user_id_fkey', 'quote', 'user', ['user_id'], ['user_id'])
    op.create_table('user',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=70), autoincrement=False, nullable=True),
    sa.Column('user_github_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_github_login', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('user_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=u'user_pkey'),
    sa.UniqueConstraint('user_email', name=u'user_user_email_key'),
    sa.UniqueConstraint('user_github_id', name=u'user_user_github_id_key'),
    sa.UniqueConstraint('user_github_login', name=u'user_user_github_login_key')
    )
    op.drop_table('tq_user')
    ### end Alembic commands ###
