"""Update icon (binary) to icon_url (string) and add some seed data.

Revision ID: 201fcaa36b3e
Revises: 83efe4f8a5d
Create Date: 2015-10-22 20:48:25.542021

"""

# revision identifiers, used by Alembic.
revision = '201fcaa36b3e'
down_revision = '83efe4f8a5d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import table, column

from tech_quote.categories import JAVASCRIPT, PYTHON


category_table = table(
    'category',
    column('id', sa.Integer),
    column('name', sa.String),
    column('description', sa.String),
    column('icon_url', sa.String))


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    category_column = sa.Column(
        'icon_url', sa.String(length=60), nullable=False)
    op.add_column('category', category_column)
    op.drop_column('category', 'icon')
    ### end Alembic commands ###
    op.bulk_insert(category_table, [PYTHON, JAVASCRIPT])


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    category_column = sa.Column(
        'icon', postgresql.BYTEA(), autoincrement=False, nullable=False)
    op.add_column('category', category_column)
    op.drop_column('category', 'icon_url')
    ### end Alembic commands ###
