"""Remove author.website column and alter column types.

Revision ID: 2825945cb5a3
Revises: 201fcaa36b3e
Create Date: 2015-11-05 18:22:55.535161

"""

# revision identifiers, used by Alembic.
revision = '2825945cb5a3'
down_revision = '201fcaa36b3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'website')
    ### end Alembic commands ###
    connection = op.get_bind()
    connection.execute(
        'ALTER TABLE author ALTER COLUMN name TYPE VARCHAR(70);')
    connection.execute(
        'ALTER TABLE author ALTER COLUMN biography TYPE VARCHAR(200);')

    connection.execute(
        'ALTER TABLE category ALTER COLUMN name TYPE VARCHAR(70);')
    connection.execute(
        'ALTER TABLE category ALTER COLUMN icon_url TYPE VARCHAR(200);')

    connection.execute(
        'ALTER TABLE quote ALTER COLUMN source TYPE VARCHAR(200);')


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'author',
        sa.Column(
            'website', sa.VARCHAR(length=60),
            autoincrement=False, nullable=False))
    ### end Alembic commands ###
    connection = op.get_bind()
    connection.execute(
        'ALTER TABLE author ALTER COLUMN name TYPE VARCHAR(60);')
    connection.execute(
        'ALTER TABLE author ALTER COLUMN biography TYPE TEXT;')

    connection.execute(
        'ALTER TABLE category ALTER COLUMN name TYPE VARCHAR(60);')
    connection.execute(
        'ALTER TABLE category ALTER COLUMN icon_url TYPE VARCHAR(60);')

    connection.execute(
        'ALTER TABLE quote ALTER COLUMN source TYPE VARCHAR(60);')
