"""Add github columns to user table, store name instead of first and last.

Revision ID: 2f08db18f860
Revises: 4910ecfa5ad5
Create Date: 2015-11-12 19:59:25.405080

"""

# revision identifiers, used by Alembic.
revision = '2f08db18f860'
down_revision = '4910ecfa5ad5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_github_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('user_github_login', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('user_is_active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('user_name', sa.String(length=70), nullable=True))
    op.create_unique_constraint(None, 'user', ['user_github_login'])
    op.create_unique_constraint(None, 'user', ['user_github_id'])
    op.drop_column('user', 'user_last_name')
    op.drop_column('user', 'user_active')
    op.drop_column('user', 'user_first_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('user_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('user_last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_name')
    op.drop_column('user', 'user_is_active')
    op.drop_column('user', 'user_github_login')
    op.drop_column('user', 'user_github_id')
    ### end Alembic commands ###
