"""Foreign key columns should not be be nullable.

Revision ID: 3cfdcd0f17fa
Revises: 133552773f96
Create Date: 2015-11-15 17:39:33.026830

"""

# revision identifiers, used by Alembic.
revision = '3cfdcd0f17fa'
down_revision = '133552773f96'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quote', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quote', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quote', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quote', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quote', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quote', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
