"""Add column for tracking an avatar url.

Revision ID: 3e2feeea07cb
Revises: 3cfdcd0f17fa
Create Date: 2015-11-25 03:20:43.124873

"""

# revision identifiers, used by Alembic.
revision = '3e2feeea07cb'
down_revision = '3cfdcd0f17fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tq_user', sa.Column('user_avatar_url', sa.String(length=200), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tq_user', 'user_avatar_url')
    ### end Alembic commands ###
