"""Add User,Role tables and reference user_id in Quote.

Revision ID: 4910ecfa5ad5
Revises: 29095d3cc367
Create Date: 2015-11-11 05:30:58.163543

"""

# revision identifiers, used by Alembic.
revision = '4910ecfa5ad5'
down_revision = '29095d3cc367'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=80), nullable=False),
    sa.Column('user_first_name', sa.String(length=30), nullable=True),
    sa.Column('user_last_name', sa.String(length=30), nullable=True),
    sa.Column('user_created', sa.DateTime(), nullable=False),
    sa.Column('user_active', sa.Boolean(), nullable=True),
    sa.Column('user_is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.add_column(u'quote', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quote', 'user', ['user_id'], ['user_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quote', type_='foreignkey')
    op.drop_column(u'quote', 'user_id')
    op.drop_table('role')
    op.drop_table('user')
    ### end Alembic commands ###
